--- Generated by Luanalysis
--- Created by anatkh.
--- DateTime: 2023/4/8 04:13
--- 1,参数列表 1.1 优惠卷id
local voucherId = ARGV[1]
local userId = ARGV[2]
--2。数据key 库存key 和订单key
local stockKey = 'seckill:stock:' .. voucherId
local orderKey = 'seckill:order:' .. voucherId
--脚本业务
-- 判断库存
if(tonumber(redis.call('get',stockKey))<= 0)then
    -- 库存不足 返回1
    return 1;
end
-- 判断用户是否下单,即判断当前用户是否在当前voucher对应的值的set中
--ismember key value
if(redis.call('sismember',orderKey,userId) == 1)then
    -- 存在则是重复下单 返回2
    return 2;
end
-- 扣减库存 incrby stockKey -1
redis.call('incrby',stockKey,-1)
-- 下单 sadd orderKey userid
redis.call('sadd',orderKey,userId)
return 0;